import { Locale } from "@/i18n/config";

export const BLOG_ITEMS: Record<Locale, string[]> = {
  en: [
    "best-words-for-charades-by-difficulty",
    "charades-for-adults-online-party-night-challenges",
    "charades-for-holidays-and-seasonal-parties",
    "charades-for-kids-online-classroom-and-birthdays",
    "charades-for-remote-teams-toolkit",
    "charades-game-night-checklist",
    "charades-ideas-for-game-night-online",
    "charades-ideas-generator",
    "charades-icebreakers-for-large-groups",
    "charades-rules-for-beginners",
    "charades-rules-variations-and-house-rules",
    "charades-strategy-advanced-tips-to-win",
    "charades-tips-for-shy-players",
    "charades-words-by-category",
    "charades-words-for-bachelorette-parties",
    "charades-words-for-birthday-parties",
    "charades-words-for-christmas",
    "charades-words-for-college-students",
    "charades-words-for-couples",
    "charades-words-for-halloween",
    "charades-words-for-kids",
    "charades-words-for-new-years",
    "charades-words-for-seniors",
    "charades-words-for-summer-parties",
    "charades-words-for-teens",
    "charades-words-for-valentines-day",
    "charades-words-for-weddings",
    "charades-words-for-workplace",
    "choosing-the-best-online-charades-game",
    "charades-on-video-call-zoom-meet-facetime",
    "dumb-charades-funny-words",
    "dumb-charades-words",
    "easy-charades-words-for-beginners",
    "easy-charades-words-for-families",
    "free-multiplayer-charades-online-with-friends",
    "free-online-charades-no-signup",
    "funny-charades-words-for-adults",
    "funny-charades-words-for-adults-hard",
    "hard-charades-ideas-for-adults",
    "hard-charades-words-for-adults",
    "host-an-online-charades-game-night",
    "how-to-make-your-own-charades-word-lists",
    "how-to-play-charades-with-kids-guide",
    "how-to-play-heads-up-charades-like-a-pro",
    "multiplayer-charades-with-friends-online",
    "online-charades",
    "play-charades-with-friends-online-complete-guide",
    "team-building-with-online-charades",
    "ultimate-charades-words-by-theme",
    "what-is-playmime",
  ],
  fa: [],
};
